### ISSUE TITLE
Version misspelling in example-flask-python3.7-index.zip's docker-compose.yml

### ISSUE THREAD

**Issue by vsund** [tiangolo/uwsgi-nginx-flask-docker#106]
The [`example-flask-python3.7-index.zip`](https://github.com/tiangolo/uwsgi-nginx-flask-docker/releases/download/v0.3.9/example-flask-python3.7-index.zip) file from the [current readme](https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/885f647bd77e8ac0fbd5f4fc3de6fc0448357cc0/README.md#examples-project-templates) states a `version: 3'` (not `version: '3'`) in its `docker-compose.yml` file (which results in an quite nasty error message when trying to start it).

For reference and probably most importantly search indexes the error message:
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.23.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.7/site-packages/compose/cli/command.py", line 42, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python3.7/site-packages/compose/cli/command.py", line 115, in get_project
    config_data = config.load(config_details, compatibility)
  File "/usr/lib/python3.7/site-packages/compose/config/config.py", line 381, in load
    validate_config_version(config_details.config_files)
  File "/usr/lib/python3.7/site-packages/compose/config/config.py", line 299, in validate_config_version
    if main_file.version != next_file.version:
  File "/usr/lib/python3.7/distutils/version.py", line 46, in __eq__
    c = self._cmp(other)
  File "/usr/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by vsund** [comment]
Somehow missed that these example folders are also tracked in this repository. Still needs a change for the zipped release file (I don't think there's a way to propose changes through a PR for these).
