### ISSUE TITLE
Python packages still not available to app after pip install

### ISSUE THREAD

**Issue by raddevon** [tiangolo/uwsgi-nginx-flask-docker#22]
I have additional requirements I need to install for my app. Here's my Dockerfile:
```
FROM tiangolo/uwsgi-nginx-flask:python3.6

ENV STATIC_INDEX 1

COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY . /app
```

Even after rebuilding, the app still can't import my packages. When I bring up the docker container, I get this in the output:
```
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    from flask_cors import CORS
```

The build step does show it installing the package.
```
Building web
Step 1/5 : FROM tiangolo/uwsgi-nginx-flask:python3.6
 ---> 590e17342131
Step 2/5 : ENV STATIC_INDEX 1
 ---> Using cache
 ---> be704d970645
Step 3/5 : COPY requirements.txt /app/
 ---> Using cache
 ---> 9a2d06e8c82e
Step 4/5 : RUN pip install -r /app/requirements.txt
 ---> Running in 85413afc84ee
Collecting certifi==2017.7.27.1 (from -r /app/requirements.txt (line 1))
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
Collecting chardet==3.0.4 (from -r /app/requirements.txt (line 2))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Requirement already satisfied: click==6.7 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 3))
Requirement already satisfied: Flask==0.12.2 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 4))
Collecting Flask-Cors==3.0.3 (from -r /app/requirements.txt (line 5))
  Downloading Flask_Cors-3.0.3-py2.py3-none-any.whl
Collecting idna==2.6 (from -r /app/requirements.txt (line 6))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Requirement already satisfied: itsdangerous==0.24 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 7))
Requirement already satisfied: Jinja2==2.9.6 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 8))
Requirement already satisfied: MarkupSafe==1.0 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 9))
Collecting requests==2.18.4 (from -r /app/requirements.txt (line 10))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting six==1.11.0 (from -r /app/requirements.txt (line 11))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting urllib3==1.22 (from -r /app/requirements.txt (line 12))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Requirement already satisfied: Werkzeug==0.12.2 in /usr/local/lib/python3.6/site-packages (from -r /app/requirements.txt (line 13))
Installing collected packages: certifi, chardet, six, Flask-Cors, idna, urllib3, requests
Successfully installed Flask-Cors-3.0.3 certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 six-1.11.0 urllib3-1.22
 ---> 0437821ea780
Removing intermediate container 85413afc84ee
Step 5/5 : COPY . /app
 ---> aed7dfd1c4a8
Removing intermediate container debc2010ff97
Successfully built aed7dfd1c4a8
Successfully tagged app_web:latest
```

Can anyone see what I'm doing wrong here? Thank you!

**Comment by tiangolo** [comment]
Can you paste a bigger chunk of your Traceback? It is not very clear what is the error it is complaining about. It's probably in that line, but we don't know the specific error in that line.

---

Also, check this section:

```
Step 3/5 : COPY requirements.txt /app/
 ---> Using cache
```

It is not copying the updated `requirements.txt` because it thinks it already has it from a previous build, so it's using the Docker cache. It's possible that it doesn't have the latest version of `requirements.txt` (after you added some more dependencies). You might want to build it with `--no-cache`: `docker build --no-cache .` or `docker-compose build --no-cache`.

That will execute all the steps, without using any cached version of your app. It will take longer but will ensure that you have the very latest version of everything.

---

There's also an alternative that allows you to be able to use the Docker cache and have faster build times. Which in turn, allows you to iterate fast while developing (this is what I normally do). 

The trick is to declare your Python packages in your `Dockerfile`, instead of the separated `requirements.txt`.

You can add a line like:

```Dockerfile
RUN pip install Flask-Cors
```

And then, when you see that you will also need `requests`, you can add another line:

```Dockerfile
RUN pip install Flask-Cors
RUN pip install requests
```

That will make your Docker build faster because it will use the previous layer that installed `Flask-Cors`, and install `requests` on top of it, instead of having to install all the packages one by one every time.

When you are done, you should compact them, to make your Docker image thinner, like:

```Dockerfile
RUN pip install Flask-Cors requests
```

But while developing it helps to be able to build the whole thing faster.

This method is less "Pythonic" (not using the `requirements.txt`) but is more "Dockeronic" (or however they say it), by taking full advantage of Docker, the cache, etc.

**Comment by raddevon** [comment]
Thank you for your help, @tiangolo!

Here's the full output from starting the container:
```
Creating network "gsawstestsuite_default" with the default driver
Creating gs-aws-test-suite-management ...
Creating gs-aws-test-suite-management ... done
Attaching to gs-aws-test-suite-management
gs-aws-test-suite-management | /usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
gs-aws-test-suite-management |   'Supervisord is running as root and it is searching '
gs-aws-test-suite-management | 2017-09-26 13:51:12,413 CRIT Supervisor running as root (no user in config file)
gs-aws-test-suite-management | 2017-09-26 13:51:12,413 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
gs-aws-test-suite-management | 2017-09-26 13:51:12,419 INFO RPC interface 'supervisor' initialized
gs-aws-test-suite-management | 2017-09-26 13:51:12,419 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gs-aws-test-suite-management | 2017-09-26 13:51:12,419 INFO supervisord started with pid 1
gs-aws-test-suite-management | 2017-09-26 13:51:13,425 INFO spawned: 'nginx' with pid 9
gs-aws-test-suite-management | 2017-09-26 13:51:13,427 INFO spawned: 'uwsgi' with pid 10
gs-aws-test-suite-management | [uWSGI] getting INI configuration from /app/uwsgi.ini
gs-aws-test-suite-management | [uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
gs-aws-test-suite-management | *** Starting uWSGI 2.0.15 (64bit) on [Tue Sep 26 13:51:13 2017] ***
gs-aws-test-suite-management | compiled with version: 4.9.2 on 10 August 2017 16:32:21
gs-aws-test-suite-management | os: Linux-4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017
gs-aws-test-suite-management | nodename: 953267145d0f
gs-aws-test-suite-management | machine: x86_64
gs-aws-test-suite-management | clock source: unix
gs-aws-test-suite-management | pcre jit disabled
gs-aws-test-suite-management | detected number of CPU cores: 4
gs-aws-test-suite-management | current working directory: /app
gs-aws-test-suite-management | detected binary path: /usr/local/bin/uwsgi
gs-aws-test-suite-management | your memory page size is 4096 bytes
gs-aws-test-suite-management | detected max file descriptor number: 1048576
gs-aws-test-suite-management | lock engine: pthread robust mutexes
gs-aws-test-suite-management | thunder lock: disabled (you can enable it with --thunder-lock)
gs-aws-test-suite-management | uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
gs-aws-test-suite-management | uWSGI running as root, you can use --uid/--gid/--chroot options
gs-aws-test-suite-management | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
gs-aws-test-suite-management | Python version: 3.6.2 (default, Jul 24 2017, 19:47:39)  [GCC 4.9.2]
gs-aws-test-suite-management | *** Python threads support is disabled. You can enable it with --enable-threads ***
gs-aws-test-suite-management | Python main interpreter initialized at 0x245bf40
gs-aws-test-suite-management | your server socket listen backlog is limited to 100 connections
gs-aws-test-suite-management | your mercy for graceful operations on workers is 60 seconds
gs-aws-test-suite-management | mapped 1237056 bytes (1208 KB) for 16 cores
gs-aws-test-suite-management | *** Operational MODE: preforking ***
gs-aws-test-suite-management | Traceback (most recent call last):
gs-aws-test-suite-management |   File "./main.py", line 4, in <module>
gs-aws-test-suite-management |     from flask_cors import CORS
gs-aws-test-suite-management | ModuleNotFoundError: No module named 'flask_cors'
gs-aws-test-suite-management | unable to load app 0 (mountpoint='') (callable not found or import error)
gs-aws-test-suite-management | *** no app loaded. going in full dynamic mode ***
gs-aws-test-suite-management | *** uWSGI is running in multiple interpreter mode ***
gs-aws-test-suite-management | spawned uWSGI master process (pid: 10)
gs-aws-test-suite-management | spawned uWSGI worker 1 (pid: 13, cores: 1)
gs-aws-test-suite-management | spawned uWSGI worker 2 (pid: 14, cores: 1)
gs-aws-test-suite-management | 2017-09-26 13:51:14,735 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gs-aws-test-suite-management | 2017-09-26 13:51:14,735 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

`ModuleNotFoundError: No module named 'flask_cors'` is probably the part you needed.

You're right it was using the cache, but that's because I had already built it once previously. I believe the requirements.txt was already current in the cache. In either case, I *do* think it successfully installed Flask-Cors (the module the app is failing to import) because of the output from the `pip install` step of the build.
```
…
Successfully installed Flask-Cors-3.0.3...
…
```

I updated the Dockerfile to install the packages explicitly instead of installing from `requirements.txt`, but the app is still fails to start because it can't find the `flask_cors` module. Here's my current Dockerfile:
```
FROM tiangolo/uwsgi-nginx-flask:python3.6

ENV STATIC_INDEX 1

# COPY requirements.txt /app/
# RUN pip install -r /app/requirements.txt
RUN pip install Flask-Cors
RUN pip install requests

COPY . /app
```

and here's the relevant bit of the output of the bringing the container up with a few extra lines on either side for context:
```
gs-aws-test-suite-management | Python version: 3.6.2 (default, Jul 24 2017, 19:47:39)  [GCC 4.9.2]
gs-aws-test-suite-management | *** Python threads support is disabled. You can enable it with --enable-threads ***
gs-aws-test-suite-management | Python main interpreter initialized at 0xc80f40
gs-aws-test-suite-management | your server socket listen backlog is limited to 100 connections
gs-aws-test-suite-management | your mercy for graceful operations on workers is 60 seconds
gs-aws-test-suite-management | mapped 1237056 bytes (1208 KB) for 16 cores
gs-aws-test-suite-management | *** Operational MODE: preforking ***
gs-aws-test-suite-management | Traceback (most recent call last):
gs-aws-test-suite-management |   File "./main.py", line 4, in <module>
gs-aws-test-suite-management |     from flask_cors import CORS
gs-aws-test-suite-management | ModuleNotFoundError: No module named 'flask_cors'
gs-aws-test-suite-management | unable to load app 0 (mountpoint='') (callable not found or import error)
gs-aws-test-suite-management | *** no app loaded. going in full dynamic mode ***
gs-aws-test-suite-management | *** uWSGI is running in multiple interpreter mode ***
```

**Comment by raddevon** [comment]
I should mention that I can run this Flask app locally on the host machine and the import works.

**Comment by tiangolo** [comment]
That's very strange, I don't see anything obviously wrong from what you show me.

Actually, I have several apps with my team that look very similar to yours.

Could you create a public repo that reproduces the error? You don't have to share your full code with me, but just a minimal example that reproduces the error.

That way I can check it more thoroughly. I think that would be faster.

**Comment by raddevon** [comment]
I tried to replicate this and was unsuccessful. The only difference between my demo app and the actual app I'm working on is that the latter uses docker-compose. I'll either rip that out altogether or try to figure out why it's causing a problem.

Thanks for your help and patience. I'll go ahead and close this issue, but, if you have any ideas why compose might be making the package unavailable to the app, please let me know.

**Comment by tiangolo** [comment]
Ok, you might want to replicate the Docker Compose part too, I could take a look at it.

I don't see anything obvious to check, it would be better to check the code and then start hypothesizing. But the first thing that comes to mind is if you have volumes declared in your Docker Compose. And if it results that one of those volumes is in the path where Python installs the packages (or the root path or something like that)... But that's a very contrived imaginary example.

If you can add Docker Compose to your demo app, then we can probably try to see what's happening.

**Comment by raddevon** [comment]
Just realized I forgot to report back on this. I ended up moving away from docker-compose. (I didn't really need it anyway; just had it in place because it makes rebuilding the image and bringing up the container a little more convenient.) Everything is working now. Thank you so much for the help!

**Comment by tiangolo** [comment]
Cool! Thanks for reporting back :+1:

**Comment by klausweiss** [comment]
Hi! I've encountered the same issue.

The problem is with the `PYTHONPATH` env variable which is being set [here](https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.6/Dockerfile#L33) - it's being overridden so the python interpreter does look for site packages just in `/app`.

While it isn't resolved, use one of the following workarounds:
1. Unset the `PYTHONPATH` env variable
```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.6
RUN  unset -v PYTHONPATH
```
2. Install pip requirements into the `/app` directory
```Dockerfile
RUN  pip install -r /app/requirements.txt -t /app
```

**Comment by tiangolo** [comment]
I'm very sorry, I tried all the ways I can think of that you could have your environment, but I can't replicate your issue.

BTW, the `PYTHONPATH` probably doesn't have anything to do with your issue. It is just a shortcut to simplify your development: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

> Augment the default search path for module files. [...]

> The default search path is installation dependent, but generally begins with prefix/lib/pythonversion (see PYTHONHOME above). It is always appended to PYTHONPATH.

---

These are the files I have in my test environment:

```
.
├── app
│   ├── main.py
│   └── requirements.txt
├── docker-compose.yml
└── Dockerfile
```

And their contents:

`Dockerfile`

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.6

ENV STATIC_INDEX 1

COPY ./app/requirements.txt /app/
RUN pip install -r /app/requirements.txt
# RUN pip install Flask-Cors
# RUN pip install requests

COPY ./app /app
```

`docker-compose.yml`

```yml
version: '2'
services:
  web:
    build: ./
    ports:
      - "80:80"
```

`app/requirements.txt`

```
Flask-Cors
```

`app/main.py`

```python
from flask import Flask
from flask_cors import CORS
app = Flask(__name__)


@app.route("/hello")
def hello():
    return "Hello World from Flask in a uWSGI Nginx Docker container with \
     Python 3.6 (from the example template)"


if __name__ == "__main__":
    # Only for debugging while developing
    app.run(host='0.0.0.0', debug=True, port=80)
```

---

Run:

```bash
docker-compose build
docker-compose up -d
docker-compose logs web
```

---

The logs I get are:

```
Attaching to testuwsgi_web_1
web_1  | Checking for script in /app/prestart.sh
web_1  | Running script /app/prestart.sh
web_1  | Running inside /app/prestart.sh, you could add migrations to this file, e.g.:
web_1  |
web_1  | #! /usr/bin/env bash
web_1  |
web_1  | # Let the DB start
web_1  | sleep 10;
web_1  | # Run migrations
web_1  | alembic upgrade head
web_1  |
web_1  | /usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
web_1  |   'Supervisord is running as root and it is searching '
web_1  | 2018-04-26 20:56:39,158 CRIT Supervisor running as root (no user in config file)
web_1  | 2018-04-26 20:56:39,158 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
web_1  | 2018-04-26 20:56:39,163 INFO RPC interface 'supervisor' initialized
web_1  | 2018-04-26 20:56:39,163 CRIT Server 'unix_http_server' running without any HTTP authentication checking
web_1  | 2018-04-26 20:56:39,163 INFO supervisord started with pid 7
web_1  | 2018-04-26 20:56:40,165 INFO spawned: 'nginx' with pid 10
web_1  | 2018-04-26 20:56:40,166 INFO spawned: 'uwsgi' with pid 11
web_1  | [uWSGI] getting INI configuration from /app/uwsgi.ini
web_1  | [uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
web_1  | *** Starting uWSGI 2.0.17 (64bit) on [Thu Apr 26 20:56:40 2018] ***
web_1  | compiled with version: 6.3.0 20170516 on 18 April 2018 07:57:51
web_1  | os: Linux-4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018
web_1  | nodename: 53b10f80a26c
web_1  | machine: x86_64
web_1  | clock source: unix
web_1  | pcre jit disabled
web_1  | detected number of CPU cores: 8
web_1  | current working directory: /app
web_1  | detected binary path: /usr/local/bin/uwsgi
web_1  | your memory page size is 4096 bytes
web_1  | detected max file descriptor number: 1048576
web_1  | lock engine: pthread robust mutexes
web_1  | thunder lock: disabled (you can enable it with --thunder-lock)
web_1  | uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
web_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
web_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
web_1  | Python version: 3.6.5 (default, Mar 31 2018, 01:01:46)  [GCC 6.3.0 20170516]
web_1  | *** Python threads support is disabled. You can enable it with --enable-threads ***
web_1  | Python main interpreter initialized at 0x559cb59b0e10
web_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
web_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
web_1  | your server socket listen backlog is limited to 100 connections
web_1  | your mercy for graceful operations on workers is 60 seconds
web_1  | mapped 1239640 bytes (1210 KB) for 16 cores
web_1  | *** Operational MODE: preforking ***
web_1  | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x559cb59b0e10 pid: 11 (default app)
web_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
web_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
web_1  | *** uWSGI is running in multiple interpreter mode ***
web_1  | spawned uWSGI master process (pid: 11)
web_1  | spawned uWSGI worker 1 (pid: 14, cores: 1)
web_1  | spawned uWSGI worker 2 (pid: 15, cores: 1)
web_1  | 2018-04-26 20:56:41,347 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1  | 2018-04-26 20:56:41,347 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1  | [pid: 14|app: 0|req: 1/1] 172.25.0.1 () {44 vars in 1515 bytes} [Thu Apr 26 20:56:46 2018] GET /hello => generated 105 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
web_1  | 172.25.0.1 - - [26/Apr/2018:20:56:46 +0000] "GET /hello HTTP/1.1" 200 105 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"
```

So, everything seems to work fine in my environment. If you have a complete public repo with specific steps that clearly shows the error, I might help you find the issue.

**Comment by shinde-prasad** [comment]
@tiangolo how can we assure that `ENV STATIC_INDEX 1` is set or not and all the modules from requirements.txt are installed into docker container?

**Comment by tiangolo** [comment]
@shinde-prasad I'm not sure if I understand. But if you mean how to check the value of the env var `STATIC_INDEX` inside the container:

* You can run a [`docker exec`](https://docs.docker.com/engine/reference/commandline/exec/) inside the container, with bash, e.g. 

```bash
docker exec -it mycontainer bash
```

* And then, inside of it, `echo` the value of the variable:

```bash
echo $STATIC_INDEX
```

**Comment by Jaysins** [comment]
@raddevon did you finally figure this out

**Comment by puhoy** [comment]
I stumbled over this when i searched for a similar issue - i was installing packages that would not show up in the final image.
The problem for me was, that the base dockerfile changed the user, so the solution was to set the user back to root with `USER root`, install what i had to install, then change it back to what was set in the base image.

**Comment by cartantino** [comment]
Hi @puhoy I am trying to solve this issue with your solution. How can you get back to the user set in the base image?
Thanks in advance.

Costantino
